services:
  # 1. BANCO DE DADOS
  db:
    image: postgres:15-alpine
    container_name: helpdesk_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      # O banco primário criado junto com o container é o do Next.js
      POSTGRES_DB: helpdesk
    ports:
      - "5433:5432" # A porta 5433 fica exposta para você usar o DBeaver
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. HELPDESK (NEXT.JS)
  web:
    container_name: helpdesk_web
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3000" # Liberado na porta 3001 para não conflitar no seu SSH
    environment:
      # Conecta no 'db' internamente no banco 'helpdesk'
      DATABASE_URL: "postgresql://admin:password123@db:5432/helpdesk?schema=public"
      # URL para o Next.js conversar com o Estoque na rede interna do Docker
      API_ESTOQUE_URL: "http://estoque:8080"
    depends_on:
      - db

  # 3. ESTOQUE (SPRING BOOT)
  estoque:
    container_name: estoque_api
    build:
      context: ./estoque
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      # A MÁGICA AQUI: Conecta no mesmo serviço 'db', mas no banco 'suprimentos'
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/suprimentos"
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password123
      # Cria as tabelas do estoque automaticamente
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

volumes:
  postgres_data: